services:
  servers:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      # Server 1 configuration
      - "traefik.http.routers.server1.rule=Host(`gym.pepo.ar`)"
      - "traefik.http.routers.server1.entrypoints=web"
      - "traefik.http.services.server1.loadbalancer.server.port=3000"
      # Server 2 configuration - Usando un subdominio virtual
      - "traefik.http.routers.server2.rule=Host(`gym.pepo.ar`) && PathPrefix(`/server2`)"
      - "traefik.http.routers.server2.entrypoints=web"
      - "traefik.http.services.server2.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/server2"
      - "traefik.http.routers.server2.middlewares=strip-prefix"
      - "traefik.http.routers.server2.priority=100"
