services:
  servers:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${COOLIFY_URL}`)"
      - "traefik.http.services.app.loadbalancer.server.port=80"  # Service handling for domain.com
      - "traefik.http.routers.api.rule=Host(`${COOLIFY_URL}`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=81"  # Service handling for domain.com/api
