services:
  servers:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server1.rule=PathPrefix(`/`)"
      - "traefik.http.routers.server1.service=server1"
      - "traefik.http.services.server1.loadbalancer.server.port=3000"
      - "traefik.http.routers.server1.priority=1"
      - "traefik.http.routers.server2.rule=PathPrefix(`/server2`)"
      - "traefik.http.routers.server2.service=server2"
      - "traefik.http.services.server2.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.strip-server2.stripprefix.prefixes=/server2"
      - "traefik.http.routers.server2.middlewares=strip-server2"
      - "traefik.http.routers.server2.priority=10"
    networks:
      - app_network

  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:3000"
      - "--entryPoints.dashboard.address=:3005"
    ports:
      - "3000:3000"
      - "3005:3005"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
