services:
  servers:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server1.rule=PathPrefix(`/`)"
      - "traefik.http.routers.server1.service=server1"
      - "traefik.http.services.server1.loadbalancer.server.port=3000"
      - "traefik.http.routers.server1.entrypoints=web"
      - "traefik.http.routers.server2.rule=PathPrefix(`/server2`)"
      - "traefik.http.routers.server2.service=server2"
      - "traefik.http.services.server2.loadbalancer.server.port=3001"
      - "traefik.http.routers.server2.entrypoints=web"
      - "traefik.http.middlewares.strip-server2.stripprefix.prefixes=/server2"
      - "traefik.http.routers.server2.middlewares=strip-server2"
    
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:8081"
      - "--entryPoints.dashboard.address=:9000"
    ports:
      - "3002:80"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=dashboard"
