services:
  servers:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app.priority=1"
      - "traefik.http.services.app.loadbalancer.server.port=3000"  # Service handling for domain.com
      - "traefik.http.routers.api.rule=PathPrefix(`/server2`)"
      - "traefik.http.services.api.loadbalancer.server.port=3001"  # Service handling for domain.com/api
      - "traefik.http.routers.api.priority=3"
