services:
  server-1:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server1.rule=PathPrefix(`/`)"
      - "traefik.http.routers.server1.priority=1"
      - "traefik.http.services.server1.loadbalancer.server.port=3000"  # Service handling for domain.com
  server-2:
    build:
      context: .
      dockerfile: Dockerfile2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server2.rule=PathPrefix(`/server2`)"
      - "traefik.http.routers.server2.priority=10"
      - "traefik.http.services.server2.loadbalancer.server.port=3001"  # Service handling for domain.com/server2
      - "traefik.http.middlewares.strip-server2.stripprefix.prefixes=/server2"
      - "traefik.http.routers.server2.middlewares=strip-server2"
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "3000:80"
      # - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
