services:
  servers:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_network

  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - servers
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
